java_library(
    name = 'intermediary',
    srcs = glob(['*.java']),
    provided_deps = [
        '//third_party/java/servlet:servlet-api',
    ],
    deps = [
        '//java/client/src/org/openqa/selenium/firefox:firefox',
        '//java/client/src/org/openqa/selenium/remote:remote',
        '//third_party/java/gson:gson',
        '//third_party/java/guava:guava',
    ],
    visibility = [
        '//java/server/src/org/openqa/selenium/remote/server:standalone-server-lib',
    ],
)
